### ISSUE TITLE
Huge security risk

### ISSUE THREAD

**Issue by PrimordialHelios** [shinigami-eyes/shinigami-eyes#1]
This extension is being used to out trans people, and is a huge security risk. As it currently stands, this is doing far more harm than any good it could possibly do. Please take it down.

**Comment by mxsparks** [comment]
At the very least, the ability to tag individual user profiles should be removed, as this places the affected users in danger of harassment or worse.

**Comment by PrimordialHelios** [comment]
@mxsparks i think that's pretty impossible, it would be very hard to distinguish between what is and isn't a user profile. better to just kill the whole thing and avoid any harm.

**Comment by tastytea** [comment]
We don't know who is behind this project, maybe a hate-group. Even if not, the data has to be hosted somewhere. Someone at that place could dump the database and put it online.

This repo should should be taken down.

THINK ABOUT THE ETHICAL IMPLICATIONS OF YOUR CODE **BEFORE** RELEASING IT!

**Comment by shinigami-eyes** [comment]
The guidelines clearly state that being trans is not enough to be marked as friendly, nor is it required. Many cisgender groups and individuals are marked green as well.

New submissions are periodically synced offline and then removed from the server.

**Comment by PrimordialHelios** [comment]
People will mark things as trans friendly regardless of whether or not it follows the guidelines. Your code is being used to mark and track trans people.

Lots of people are questioning your motives, and I think this confirms it. You are acting and bad faith and collecting data on trans people.

**Comment by shinigami-eyes** [comment]
There are mechanisms in place to ignore bad quality submissions.
Also, since some people have expressed doubts about me being an alt-righter or terf posing as a trans person, here is a letter thanking me for donating a few hundred dollars to a trans rights organization, and some HRT medications. https://i.imgur.com/ZxOMFWI.jpg

**Comment by moggers87** [comment]
> There are mechanisms in place to ignore bad quality submissions.

Such as?

> Also, since some people have expressed doubts about me being an alt-righter or terf posing as a trans person, here is a letter thanking me for donating a few hundred dollars to a trans rights organization

That proves nothing other than the fact that you've given money to a trans rights org. It tells us nothing of how you will handle the data gathered - which is the thing we're most concerned about. You're being very quiet about what happens behind the scenes and that is quite concerning - you out right refused to explain anything in #2 for example.
