### ISSUE TITLE
Extension now being abused for unrelated geopolitical issues...

### ISSUE THREAD

**Issue by Invertex** [shinigami-eyes/shinigami-eyes#134]
As a long time user of this add-on, it's mostly been a great asset to use for identifying bigoted/anti-LGBTQ+/alt-right type folk so I can avoid/block them or get a better frame of reference for their behavior.

But recently I'm noticing things being marked anti-trans that have nothing to do with these issues.

The primary one seems to be people wanting to abuse this tool to mark any company still operating in Israel or Russia as "anti-trans", which is an abuse of the purpose of this addon. This isn't supposed to be a "people I feel are just bad" addon. 
And in the case of one big example, Burger King, they celebrate LGBTQ+ and even did a counter charity against Chick-Fil-A's anti-LGTBQ+ actions/statements... Yet because some franchisees still exist in Israel/Russia they're now marked red...

But I'm not sure what could be done about it either without creating some sort of feedback and references system to back up claims, something more akin to Community Notes on Twitter. 
I fear this addon is becoming progressively less useful now as the trust in reasoning for a rating drops.

**Comment by shinigami-eyes** [comment]
> people wanting to abuse this tool to mark any company still operating in Israel or Russia as "anti-trans"

I can confirm. Significant effort went into minimizing the influence of such irrelevant submissions.

> Burger King

This is a big mistake of version 1.0.36, even though it doesn't stem from the I/P conflict.

**Comment by TCPMYT** [comment]
Are we forgetting burger king killed a woman and blamed it on her HRT?

**Comment by Invertex** [comment]
"Burger King" did not kill her, Burger King is a franchise, and one franchisee/manager of a location made a bigoted comment about her death, that is an important distinction when throwing around claims, locations are independently owned and operated.

Burger King the corporation responded saying such comments are inaccurate and unacceptable.
They've also shown plenty of public support and fundraising for LGBTQ+ causes.
