### ISSUE TITLE
(ACCESSIBILITY) add colorblind option or change colors of labels

### ISSUE THREAD

**Issue by huckleton** [shinigami-eyes/shinigami-eyes#17]
after looking at feedback from people who use tumblr, a few people with red-green colorblindness (not me) have reported issues with the red/green colors of the labels. i suggest changing the colors  or adding an option to do so to something that can be recognized as "friendly/unfriendly" while being colorblind-safe, such as dark red (unfriendly) and light blue (friendly).

**Comment by shinigami-eyes** [comment]
Version 1.0.20 introduces new color schemes for colorblind people.
