### ISSUE TITLE
Server source code missing

### ISSUE THREAD

**Issue by moggers87** [shinigami-eyes/shinigami-eyes#2]
I see that this extension speaks to https://shinigami-eyes.azurewebsites.net/api/submit but I don't see the source code for it anywhere.

Given the sensitive nature of the data that are being collected (see #1) I think it would be best that source code for the server be released as well.

**Comment by shinigami-eyes** [comment]
The submission code is a short Azure Function that simply saves the JSON to an Azure Blob.
The rest of the processing is done offline (after the data is synced). Given the sensitive nature of the topic (and presence of adversaries), I don't plan to reveal the specifics of how a group of submissions is considered good enough to be accepted and made available to all users.

**Comment by PrimordialHelios** [comment]
So you admit this is sensitive data? Then why are you collecting it?

**Comment by moggers87** [comment]
OK, should I open another issue to ask for details of how this data is processed?

**Comment by PrimordialHelios** [comment]
@moggers87 Do it. Let's keep asking questions and exposing why this is a bad idea until the maintainer realizes they need to shut this down.

**Comment by moggers87** [comment]
@shinigami-eyes your answers have been curt and don't fill me with much confidence. If you really believe your software is not open to abuse then humour us and answer our questions. For example, you've still not told us how the data is stored on your server - how anonymous is it? If you were hacked, what would be a stake?

I run a small email anonymisation service; I have to field all sorts of questions and even have to back out entire features because of user concerns about security and abuse. When writing software that deals with sensitive or personal data, one cannot decide "yes this is secure because i say so" - you have to do a lot of talking!
