### ISSUE TITLE
Public service announcement

### ISSUE THREAD

**Issue by Xetanai** [shinigami-eyes/shinigami-eyes#26]
Just an outsider here, figuring I'd try to clear things up and explain the current situation objectively seeing as the user spamming issues is seemingly beyond reason and has blocked me to prevent me from clearing up said lies.

The controversial feature of this extension is one that allows people to mark users on various sites as transphobic or trans friendly. In no way does it out anybody as trans, though that doesn't really matter as much as the real problem.

The problem arises from the fact that if a user is marked trans-friendly, and resides in a part of the world where such a viewpoint would be dangerous to broadcast publicly. There is currently no way for users to opt out of this tagging, and rather than raise an issue on this specifically, they've opened several issues over the last few days with few mentioning the root problem, and some harassing the author and baselessly calling them a TERF, prompting some others to do the same.

I understand this person fears for their safety, and possibly that of some close to them, but creating an excess of issues will not do anything but delay the fix they're advocating for, and possibly cause the developer to drop the project (which would counterproductively make the feature permanent.)

I urge those of you linked here from other sources to not join the witch hunt and instead support his one issue requesting an opt-out for users. This is still an issue that needs to be fixed, but it is not grounds for harassment and spam.

**Comment by Xetanai** [comment]
TLDR, friendly request to keep things civil rather than flooding the repository with issues based on what's being spread around

**Comment by Laurelai** [comment]
Id like to reiterate the point that someone has to publicly make very pro trans statements to get marked as positive. State actors do not need a browser plugin to find trans allies. They have state agencies for this purpose who have more power and resources and means than this simple plugin. State actors have means beyond regular people, and use them when it suits them. 

The asymmetry of power between a regular person and a repressive state actor is staggering. They have tools like deep packet inspection and will do things like save everything going through their internet to search for people and ideologies they dont like.

This app is frankly small potatoes and its hihgly unlikely that a state actor would use it.

While adding such an opt out feature i dont think would hurt anything lets not pretend like this is actually putting someone in danger as the person who made such a claim has consistently lied regarding just about everything else they said.

A polite "hey can we make trans positive opt in" at the start probably would have gotten further than what some people here are trying to do.

While i am not the developer (and i have no envy for the position they have been thrust in) from my own experiences in being cyber harassed i can tell you that it makes things very hard. Thats what those other people are doing is engaging in a cyber harassment campaign. The goal isnt to improve the app, they all have stated outright the goal is to destroy it.

And as we both have seen the truth doesnt matter to them at all.

**Comment by Xetanai** [comment]
You're correct in the points that one has to publicly demonstrate they're an ally to be marked as such (assuming it's 100% accurate), but there's right to be concerned about the fact that users can be flagged as allies without their consent or knowledge.

In the end, it's less a trans issue and more a privacy issue. I have no doubts that removing or amending that feature will appease those that aren't here to troll and flame.

**Comment by Laurelai** [comment]
How is it a privacy concern when its based on their public posts. Im autistic fyi and genuinely do not understand the logic behind this.

**Comment by Xetanai** [comment]
Also, I feel like the concern is less about state actors and more about random folks online. This tool makes it extremely easy for trolls, or worse, to find people to harass.

**Comment by Xetanai** [comment]
Not everyone wants their information so easily accessible, regardless of if it can be found with effort. The same reasoning is given to justify doxxing, and yet doxxing is still considered a huge breach of privacy

**Comment by Laurelai** [comment]
Those people aready have their own tools that they use and have had access to much longer than this plugin existed. Theres already databases our enemies have with info on trans people and trans allies, they have bots that scrape keywords off the internet to look for victims. They have lists of people they target, i should know im a target *of* these people. This plugin is nothing like that and me being wary of that happening is why i tried it out, tested it and observed others using it.

Like to be real frank here trans people are way behind in the digital arms race and this gives our enemies nothing they didnt already have. In fact what they have is more advanced than this. Our enemies have vocally stated they too wish to see this gone and have shown no desire to use it beyond a few people trying to give it dirty data which got rejected by the developer and rightfully so.

It doesnt even require them to use effort to find us, its already an automated process for their side.

Its also differently than doxxing because if someone pays money to do a people search on you and looks up rental or property records to find your address its not your fault because you didnt post your own home address on twitter. 

Its a breach of privacy because you didnt authorize that information to the public. When you publicly post about your strong feelings about the rights of others its the equivalent of standing at a podium in front of a crowd and saying it in a microphone. If someone records it they arent violating your privacy, you didnt have a reasonable expectation of it since you made public speech on a platform for all to hear.

**Comment by Xetanai** [comment]
Regardless of one's personal beliefs of how public one's internet fingerprint is, or their personal definition of doxxing... The general consensus is that compiling or otherwise making more accessible information about a person without their consent is a beach of privacy. Throwing opinions entirely to the side and looking only at law, it is a GDPR violation as is well-outlined in this issue https://github.com/shinigami-eyes/shinigami-eyes/issues/19

Take this example. Someone lives in a country where it would be dangerous to publicly support trans rights. They're in a closed group and show support within that circle of trusted people. Their support would be difficult to discover.

This extension would serve to undo that care.

**Comment by Laurelai** [comment]
Well im not a lawyer but i read a thread where someone tried reporting this as a GDPR violation weeks ago and got zero results so it may be safe to assume the authoritative bodies who enforce GDPR dont see it as a violation.

>Take this example. Someone lives in a country where it would be dangerous to publicly support trans rights. They're in a closed group and show support within that circle of trusted people. Their support would be difficult to discover.

>This extension would serve to undo that care.

No it would not as only public posts are checked by the app. Posts in a closed group would not be visable to the public and thus the developer would have no way to verify the marking and it would get rejected.

**Comment by Xetanai** [comment]
Unless the developer were also in that circle. Moreover, the server end of things is a black box and you have to trust the judgement of the developer 100%.

Clearly, not everyone does.

**Comment by Laurelai** [comment]
If it was not a black box then people would be screaming about the database being public. They cant have it both ways. Either the developer puts the database in public and gets yelled at for putting peoples names on a list or they keep it black box and get yelled at for lack of transparency. Its a weird little catch 22 isnt it?

**Comment by Xetanai** [comment]
You seem to have misinterpreted what I meant.

The database is effectively public already.
Additionally, publishing the server code does not mean the database would be pushed (that's generally seen as bad practice anyways).

**Comment by Laurelai** [comment]
Referencing this https://github.com/shinigami-eyes/shinigami-eyes/issues/2#issuecomment-455857368 the developer seems to have already explained how the server side works. A short google search shows how this function works in detail.

https://www.cyotek.com/blog/upload-data-to-blob-storage-with-azure-functions

**Comment by Xetanai** [comment]
Once again, it still requires full trust in the developer. A level of trust that isn't the default for most all people. Their description was basic and is not enough to satisfy people nor enough to excuse the problem this extension has.

Your link only describes functions storing data in general. Not in this case specifically.

**Comment by Laurelai** [comment]
Nobody is being forced to install the add-on. You are right that it requires trust. If they dont trust the add on, dont use it. However trying to deny it to the people who do trust it is kind of silly.

Like i get that you are genuinely trying to be impartial here and thats cool but to me those other people seem to be trying to make a mountain out of a molehill. I also do genuniely apprecciate you trying to explain your reasonings here even if i dont agree with them. 

Would it be nice if the exact code to move data from point a to point b in format y was there, yeah sure it would be nice. Is it a dealbreaker? Not for me or many other people and i can think of several good reasons why they might not have wanted to include it.

**Comment by Xetanai** [comment]
The problem is that it's affecting people who aren't using it. That's the entire point of concern. You can't just "not use it" and have the data it has on you disappear.

People who have never even heard of this extension are being outed by it, and that's not okay.

I believe the developer has good intentions in making and maintaining this, and I also believe most of the people raising a fuss are just doing so to troll or cause a fuss. Personally I don't mind if I'm in the database.

But I fully understand why people are upset that they are in without consent and are frustrated that there is no medium to be removed.

**Comment by Laurelai** [comment]
> The problem is that it's affecting people who aren't using it. That's the entire point of concern. You can't just "not use it" and have the data it has on you disappear.
> 
> People who have never even heard of this extension are being outed by it, and that's not okay.
> 
> I believe the developer has good intentions in making and maintaining this, and I also believe most of the people raising a fuss are just doing so to troll or cause a fuss. Personally I don't mind if I'm in the database.
> 
> But I fully understand why people are upset that they are in without consent and are frustrated that there is no medium to be removed.

I do not believe anyone has actually been outed by this extension as the person who made that claim has lied repeatedly on just about everything they have said as well as changed their story multiple times. I do not trust their claims. On one hand they asked for the developer to prove they were trans, and when they did with personal info redacted they said it wasnt good enough and could have been made up.

They lied to my face *about me*, they lied about a facebook page, they lied and said i stalked them when i replied to a mastodon thread *they linked me here on github*. 

On the other hand when i asked them for proof of this app outing them they refused to even share any proof even when i stated outright i would accept it if they redacted their own personal information.

Quite frankly they are lying and their claims cannot be taken seriously.

**Comment by Xetanai** [comment]
Regardless of your belief on if it has already happened, it can and is likely to happen. Regardless of if it can happen, it's bringing to attention information not everyone wants so easily visible.

There simply is no justification to keep it as is.

**Comment by Laurelai** [comment]
Again i diagree for the reasons i stated above. I dont think its likely at all. If someone confronts you for example about being marked green and asks if you are trans, and you arent out yet you can always say no. 

Many cisgender people and pages have been marked as green and assuming someone is trans just based on that would give you too many false positives to be reliable.

Our enemies already have more accurate tools for this and yes it matters to them too because it changes how they attack someone. 

At this point we are debating in circles.

**Comment by mikegogulski** [comment]
> possibly cause the developer to drop the project (which would counterproductively make the feature permanent.)

I haven't read the code terribly deeply, but if the extension loads the bloom filter from Azure every time it starts up, then the developer canceling or defaulting on payments to that service would make the extension stop working.

**Comment by terftracker** [comment]
Hi all, I've been following this for a while now, and it seems that while everyone involved wants to keep track of TERFs and transphobes on the internet, there are some concerns about people being marked as trans allies without their consent, by an anonymous developer with unknown criteria.

For the past few days, i've been working on [TERF Tracker](https://github.com/terftracker/terftracker), a browser extension that tracks TERFs on the internet much like Shinigami Eyes, but without the potential issues that may arise from marking people as pro-trans. It's my first webextension, and it's a bit... shall we say pre-alpha?

The goals of TT are to track TERFs online, while not relying on any one developer or backend, and being easy for the user to configure. While TT is currently not ready to be used, it's pretty close. It works for marking individual facebook users (not sure about pages), and is user-configurable (provided that the user knows JSON). I intend to add support for Reddit and Youtube, and I'd like to support Twitter, but I'd need some help testing as I don't have a Twitter account. I also intend to make it much more user friendly, and change the current single list of users to a format more like what Ublock uses, with independent lists, and a context menu.

Hope to see some of you around :)

**Comment by terftracker** [comment]
I just realized this might seem like me trying to piggyback off of or compete directly with Shinigami Eyes, and that's not my intention at all. I just wanted to give people that are concerned another extension to work with.

TT has a list of TERFs/queermisics to track that's initialized on first startup and can be found [here](https://github.com/terftracker/terftracker/blob/master/assets/initial_list.json) (currently just placeholder testing values). I hope we can all work together and that TT and Shinigami Eyes can share lists, so that everyone benefits :)

**Comment by terftracker** [comment]
>If someone confronts you for example about being marked green and asks if you are trans, and you arent out yet you can always say no.

I'm really sorry to butt in, but I just wanted to address this really quickly. This is a super privileged view to hold. There very much are places in the world where people do not care if you are trans or not. If you support trans people at all, you're as good as dead.

There's a movie I think you should watch called *God Loves Uganda*. CW for just about everything you can imagine, though. It's a documentary about Christian evangelicals going to Uganda to proselytize. There's a part in the movie where a magazine (called "Rolling Stone", oddly enough) prints a list of "Uganda's top homos". Many of them, including David Kato, a prominent member of the documentary, are killed.

Having the ability to say "well, I'm not trans, I just support my friends" is incredibly privileged. There are places (even in the US) where people don't care. They either think that anyone supporting queer people must also be queer, or they just hate cishets who are pro-queer as well, and would kill anyone marked as green by this extension. Whether or not SE is outing people, there very much are areas of this country and world where being marked green would be a death sentence.

You say that you have to openly be pro-trans to be marked green, but how do you know that? Have you seen the source code? Do you trust the developer 100% to stick strictly to the guidelines they've published?

There's also this, from earlier in the thread: "i can think of several good reasons why they might not have wanted to include it.". If there are reasons not to include the server backend, then I would argue that the backend code is inherently harmful. Security by obscurity is not security.

**Comment by terftracker** [comment]
Also, someone making publicly pro-queer statements may not want to be *instantly identifiable* as pro-queer.

I'm bi, I'm trans, I make statements in support of both of those things, but I do not want someone to be able to see my username on Facebook and instantly know that I support those things. Much the same way that I'm mentally ill and neurodivergent, and while I openly support those things, I don't want people to instantly be able to know those things about me.

As it is now, TERFs and transphobes have to go digging through profiles in order to find targets. That's why their targets are almost exclusively twitter profiles where trans women talk about their daily experiences being trans, because they can tell at a glance if someone is trans or not. Having an extension that marks us and our allies lowers the barrier to entry for TERFs to find and harass us.

That's why we want an extension like this, so we can tell at a glance who our enemies are. Unfortunately, Shinigami Eyes comes with the side effect of letting our enemies do the exact same thing to us.

I feel like I'm monopolizing this and I'll stop now, sorry ^^'

**Comment by Laurelai** [comment]
> > If someone confronts you for example about being marked green and asks if you are trans, and you arent out yet you can always say no.
> 
> I'm really sorry to butt in, but I just wanted to address this really quickly. This is a super privileged view to hold. There very much are places in the world where people do not care if you are trans or not. If you support trans people at all, you're as good as dead.
> 
> There's a movie I think you should watch called _God Loves Uganda_. CW for just about everything you can imagine, though. It's a documentary about Christian evangelicals going to Uganda to proselytize. There's a part in the movie where a magazine (called "Rolling Stone", oddly enough) prints a list of "Uganda's top homos". Many of them, including David Kato, a prominent member of the documentary, are killed.
> 
> Having the ability to say "well, I'm not trans, I just support my friends" is incredibly privileged. There are places (even in the US) where people don't care. They either think that anyone supporting queer people must also be queer, or they just hate cishets who are pro-queer as well, and would kill anyone marked as green by this extension. Whether or not SE is outing people, there very much are areas of this country and world where being marked green would be a death sentence.
> 
> You say that you have to openly be pro-trans to be marked green, but how do you know that? Have you seen the source code? Do you trust the developer 100% to stick strictly to the guidelines they've published?
> 
> There's also this, from earlier in the thread: "i can think of several good reasons why they might not have wanted to include it.". If there are reasons not to include the server backend, then I would argue that the backend code is inherently harmful. Security by obscurity is not security.

Im gonna be real with you here ive talked to people in such vulnerable positions before. Like i know some of these people. The ones who speak out publicly are people who are willfully challenging the system they live under. Others wont speak a word of it in public and will only discuss it behind tor and a crytographic wall. The rest simply stay silent on the issue online.

You see they *know* they live in an oppressive area. 

This is part of why i have zero belief in the claims of that one person. 

Its one thing to watch a movie and think you know how things are its another to be involved with these folks. 

I get you want to promote your new thing but trying to create a panic about something thats not actually very likely is unethical. 

Like ive just been witnessing a whole host of bs reason after bs reason and now some unknown person tries to promote their alternate app. 

The last person to use the term "Terf Tracker" trying to do something similar to you was Allison Woolbert. How do we know you arent her?

**Comment by terftracker** [comment]
>I get you want to promote your new thing but trying to create a panic about something thats not actually very likely is unethical.

I'm definitely not trying to do that, and I'm sorry that it comes off that way. These are the actual issues I have with this. I'm certainly not panicking, I'm just not okay with giving transphobes yet another way to keep track of who we are.

Let's put it this way. Is there any *good* reason for this feature? What's the use case for it? Let's completely ignore any problems anybody might have, and just look at that one question. I see no reason to include it. Do you think there's a good reason for it? If so, what is it?

>The last person to use the term "Terf Tracker" trying to do something similar to you was Allison Woolbert. How do we know you arent her?

I'll be real, I've never heard that name before. I just thought "TERF Tracker" was a catchy name. After googling, all I can really find is stuff from r/gendercritical, and some blog called "genderidentitywatch", neither of which I'm willing to believe.

How do we know that Shinigami Eyes isn't run by Allison Woolbert? Is the only issue you have with the name I chose? If so, I'll be more than willing to change everything on Github.

**Comment by Laurelai** [comment]
>Let's put it this way. Is there any good reason for this feature? What's the use case for it? Let's completely ignore any problems anybody might have, and just look at that one question. I see no reason to include it. Do you think there's a good reason for it? If so, what is it?

Helping allies find each other, avoiding friendly fire. Our enemies. Already. Know. This. Info. We are way behind the digital arms race.

>I'll be real, I've never heard that name before. I just thought "TERF Tracker" was a catchy name. After googling, all I can really find is stuff from r/gendercritical, and some blog called "genderidentitywatch", neither of which I'm willing to believe

Then you didnt look hard enough because im the one who wrote the expose on her for transadvocate and my personal blog. The article included her conviction records, and she admitted it was true. Shes a convicted pedophile who ran a project called terf tracker and the trans violence tracking project. 


>How do we know that Shinigami Eyes isn't run by Allison Woolbert? Is the only issue you have with the name I chose? If so, I'll be more than willing to change everything on Github.

Allison wouldnt be taking grey market androcur

**Comment by terftracker** [comment]
>Helping allies find each other, avoiding friendly fire. Our enemies. Already. Know. This. Info. We are way behind the digital arms race.

The allies who want to be found make it clear who they are. There are allies out there who are fragile, and can't handle abuse. They don't want to be found, and forcibly exposing them isn't a great thing to do. I appreciate that you're doing everything you can to help other trans people, thank you. Unfortunately, there are people who are allies, but "everything they can do" is very limited, and taking abuse is not something they can do.

>Then you didnt look hard enough because im the one who wrote the expose on her for transadvocate and my personal blog. The article included her conviction records, and she admitted it was true. Shes a convicted pedophile who ran a project called terf tracker and the trans violence tracking project.

Well, that's fucking horrible, and I'll definitely be changing my username and the name of the project.

What can I do to convince you I'm not Allison?

**Comment by Laurelai** [comment]
>What can I do to convince you I'm not Allison?

You already have, she couldnt handle being challenged in any way and lashed out at anyone who did violently. If you were her you would have exploded on me.

**Comment by terftracker** [comment]
I'm glad you don't think I'm her. Like I said though, I'll be changing the name of this project, any affiliation with someone like that would be disrespectful to the people she hurt.

I'll think about names over the coming days. If you have any suggestions, please feel free to let me know :)

Any way, I feel like this discussion is getting a bit too heated, so I'll be stepping out. Feel free to use my extension, or don't. It's simply an alternative. The initial list of transphobes  is open and readily available, so feel free to use that to complement Shinigami Eyes.

**Comment by Laurelai** [comment]
And now we have the real reason for this. PrimordialHelios started this whole shit fight just so they could create a competing app.

https://github.com/terfbullet/TgTbT/graphs/contributors

https://github.com/terfbullet/TgTbT/graphs/contributors?from=2019-05-19&to=2019-05-28&type=c



terfbullet = PrimordialHelios 

So you manufactured all of this drama for the sole purpose of creating a competing app and poisoning the reputation of the person who made this one. You have no integrity and i have no faith in your ability to remain objective when it comes to determining who is and isnt a terf. 

Since you were willing to lie about the developer you will lie about anyone you dont like. You cant be trusted.

**Comment by terfbullet** [comment]
No, actually. I am PrimordialHelios, but I created this project because there are issues with SE.

Know the best part about TgTbT? It's configurable. You don't need to trust me at all, unlike SE

>Since you were willing to lie about the developer you will lie about anyone you dont like.

Rich, coming from you, who started an entire thread filled with lies, and trying to get your friends to dogpile and harass me.

I started talking to you on this account because I realized I was an ass to you, and I was hoping maybe we could have a civil discussion. But I guess not.

**Comment by Laurelai** [comment]
You have no room. Dont ever interact with me again.

**Comment by terfbullet** [comment]
Says the one lying about me fucking DDOSing her site

**Comment by Xetanai** [comment]
Ok so let me get this straight. You started a witch hunt, verbally abused anyone that called you out on it, lied repeatedly about topics that should never be joked about just so you could force a sense of urgency, harassed and insulted the owner, spammed this repository with issues, and then capitalized on the chaos to advertise your own alternative?

And you expect anyone to believe that last part is just coincidental?

You're more disgusting than any terf I've ever met.

**Comment by thebjorn** [comment]
> Well im not a lawyer but i read a thread where someone tried reporting this as a GDPR violation weeks ago and got zero results so it may be safe to assume the authoritative bodies who enforce GDPR dont see it as a violation.

@Laurelai this doesn't seem to be correct as of 2022-06-14: https://www.datatilsynet.no/contentassets/2d7e7acc2e4548fa8aca6f17dc3267b8/21_02455-11-ban-on-processing---shinigami-eyes-295856_7_1.pdf

(the decision was published in their weekly newsletter)

**Comment by MarmoraKeef** [comment]
> Not everyone wants their information so easily accessible, regardless of if it can be found with effort. The same reasoning is given to justify doxxing, and yet doxxing is still considered a huge breach of privacy

Most websites have a thing where you can search profiles. You don't have to use effort. You search their username and a word and see all the posts with it. Kind of invalidates that. 
Also, I get being outed as an ally is dangerous. Believe me. But if your profile is easy to see and it can be gleaned enough to be marked in this? Then people would already know. If you're somewhere unsafe and sharing those ideas, then you need to either be aware and doing so willingly, or lock your accounts. That is basic common sense. 
This is helpful to a lot of people. Maybe they could remove the friendly marker, or make it so only if you have the browser and agree you will be added (unless you're like a 15 million follower Twitter or something). 
Also why does everyone keep downvoting Laurelai? Everything said is right. 
This is the internet. If you say it on an unlocked account, IT IS ALREADY PUBLIC. Too many people nowadays know NOTHING about internet safety and it's pathetic and scary as hell.
