### ISSUE TITLE
GDPR violation

### ISSUE THREAD

**Issue by celesteh** [shinigami-eyes/shinigami-eyes#3]
Collecting data about people without permission is not allowed under the GDPR. This add-on is illegal in Europe.  The fact that it calls home to the developer makes you a data controller. The fines for breaking the rules on this are not small.

This is related to issue #1. Any tagged profile has rights under the GDPR.

**Comment by PrimordialHelios** [comment]
@shinigami-eyes absolutely amazed that you've completely disregarded this.

**Comment by TheBlackParrot** [comment]
@shinigami-eyes any update on this? would love to use the extension but the centralized stuff is making me uneasy (mentioning #14 too)

**Comment by PrimordialHelios** [comment]
@TheBlackParrot the responses of the maintainer scream (to me at least) that they have bad intentions. i wouldn't trust any of this

**Comment by mikegogulski** [comment]
Here's a template people might want to use for reporting the extension to Mozilla and Google (related to #1):

This extension Shinigami Eyes, while well-intentioned, presents several risks to the people it intends to serve, may be in violation of law, and presents potential legal and reputational risks to your organization.

The extension uses some CSS manipulation to color social media profiles on various sites (Facebook, Twitter, Reddit, Tumblr) as green to indicate that they are “trans friendly”. 

Risks to transgender people:

1: Trans people may end up on the “trans friendly” list without their knowledge or consent.

2: Anyone using the extension might assume that anyone tagged as “trans friendly” is transgender themselves. This will certainly contribute to outing some vulnerable people before they are ready, and without their being aware of it.

3: The alt-right, 4chan, trolls, and transphobic people in general could use the extension to compile lists of people to use as targets of online harassment, bullying, outing, doxxing, cyberstalking, and even real-life assault. This is extremely likely to happen, in fact, as some of those people are already aware of it.

Risks to your organization:

1: This extension may be illegal under the EU’s General Data Protection Regulation 2016/679, as it collects user personal data without consent and stores it in a centralized database. Your organization might be subject to accessory liability for suits prosecuted on this basis.

2: Reputational damage in the event of Shinigami Eyes-facilitated harassment/bullying/etc. campaigns.

Thank you for your consideration. We ask you remove this extension, swiftly.

**Comment by Laurelai** [comment]
You people are trying to ruin a good thing for reasons i cannot fathom. Stop it.

**Comment by PrimordialHelios** [comment]
@Laurelai it's been explained almost a dozen times now. If you truly can't understand, then why not ask?

**Comment by Laurelai** [comment]
Ive read your explainations and find them wanting,

**Comment by PrimordialHelios** [comment]
You don't think that a GDPR violation that outs trans people is bad?

**Comment by Laurelai** [comment]
The marking isnt for being trans its for being trans friendly. Assuming anyone pro trans must be trans is transphobic in itself. 

Secondly we know nothing of the creator and if they dont live in the EU then GDPR doesnt really apply to them. 

Third, this app actually does help people avoid terfs and transphobic people. 

Its helped me a lot. Now because of your absurd witch hunt on someone clearly just trying to help instead of say going after transphobes or nazis ive forked the project, if you do manage to get it taken down i promise you ill republish it myself and im definitely int he USA and GDPR definitely doesnt apply to me.

**Comment by Laurelai** [comment]
Ask yourselves if you really want *me* to be the one publishing this app and then consider your options. :)

**Comment by PrimordialHelios** [comment]
the GDPR most certainly applies to people outside the EU, that's the most ignorant thing I've ever read about the GDPR.

But no. I don't want a rapist collecting info on potential victims

**Comment by Laurelai** [comment]
You whine about gdpr but engage in libel. Alright. 

Oh and you trying to sic your followers on me based on lies is really now doing yourself any favors.

https://soc.punktrash.club/notice/9j7DE8GBXTCvCLAopU

Also the terfs reaction to this is also trying to get this taken down. Weird how yall have the same response as them.

Super weird.

**Comment by PrimordialHelios** [comment]
@shinigami-eyes you have a known rapist threatening to mass-dox trans people

this is on you

**Comment by PrimordialHelios** [comment]
You wanna dox trans people? Drop yours first, fam. See how well that works for you.

**Comment by Laurelai** [comment]
Your the one claiming something i never said. Keep being histrionic and see how credible that makes you look.

**Comment by PrimordialHelios** [comment]
Gaslighting too now? Was that what you did to your rape victims?

**Comment by Laurelai** [comment]
You are literally the one who is claiming i said something i did not and you are doing it on purpose.

**Comment by mikegogulski** [comment]
TL;DR: Calm your tits

May I suggest, in the spirit of what issues threads are for, that we confine ourselves to matters of tech, risk, and legality, rather than attempting to litigate conflicts not pertinent here?

There are certainly strong feelings on both sides of this, but this is not a forum for personal attacks and allegations - no matter how real or traumatic those might be.

**Comment by PrimordialHelios** [comment]
Sorry, I get upset when a known serial rapist of trans people threatens to begin collecting the private information of trans people. The way she even threatened to publish this makes it clear she knows that what she's doing is terrible.

She's not acting in good faith.

**Comment by Laurelai** [comment]
You have a history of accusing people of doxxing when thats not what they are doing. 

https://dragon.style/@anthracite/100722204987423828

You also have a history of apparently attacking systems of moderation and community managment too.
Weird how your shrieks of doxxing (which i would not do if i published a copy of the app and never said i would) seem to coincide with attempts at community managment.

**Comment by celesteh** [comment]
I'm going to close this issue if you don't stop with the personal attacks.

**Comment by PrimordialHelios** [comment]
Go right the fuck ahead, defend a known rapist who works with TERFs

**Comment by Laurelai** [comment]
See what im talking about? Now shes just tacking on more and more libel to get her way.

**Comment by celesteh** [comment]
Jesus Christ

**Comment by PrimordialHelios** [comment]
You work with Randi fucking Harper, a known TERF

**Comment by Laurelai** [comment]
I hate randi harper and she had me on her shitty blocklist she put trans activists on you absolute dope

**Comment by mikegogulski** [comment]
I'd've closed the issue too. What a disaster.

**Comment by mikegogulski** [comment]
fuggit, I'll open a new issue and let them fight in the comments all day

**Comment by PrimordialHelios** [comment]
I apologize for letting my emotions get the best of me. I've blocked the other person involved and will be refraining from any discussion on this repo.

**Comment by mikegogulski** [comment]
@PrimordialHelios Understandable. I hope you continue weighing in someplace, though, like maybe at #19 (though you won't see L's comments). Your comments and issues here were a big part of me deciding to blow this open today, which I thank you for.

**Comment by PrimordialHelios** [comment]
@mikegogulski I'm glad I influenced your position on this, but I think my getting more involved will only hurt our position, I'm just too angry these days :P
