### ISSUE TITLE
Extension is down on the chrome web store.

### ISSUE THREAD

**Issue by solonovamax** [shinigami-eyes/shinigami-eyes#51]
Webpage 404's: https://chrome.google.com/webstore/detail/shinigami-eyes/ijcpiojgefnkmcadacmacogglhjdjphj

Currently the only way to load it is by `git clone`ing and then loading as an unpacked extension.

**Comment by saschanaz** [comment]
This definitely has something to do with #48.

**Comment by saschanaz** [comment]
It's up again. Hooray!

**Comment by solonovamax** [comment]
Closing because it's back up.

**Comment by solonovamax** [comment]
Closing because it's back up.
