### ISSUE TITLE
New allegations against someone who currently or in the past has worked on this extension

### ISSUE THREAD

**Issue by transgirlphoebe** [shinigami-eyes/shinigami-eyes#70]
TW for rape and abuse,suicide mentions

I ask someone OTHER than the accused to please have a look at this thread: https://twitter.com/SailorHaumea/status/1498833012234067975?s=20&t=ShjWLeN6GtzvGnSW_GGm9w

Archives: https://web.archive.org/web/20220302055826/https://twitter.com/SailorHaumea/status/1498841121342038016

https://archive.ph/gPcEV

i only made archives due to the fact people like the accused will go out of their way to get accounts suspended

i noticed shes commented on issues as early as 2021 so she definitely was involved in the past.

Have a great day,and please do the right thing,ive uninstalled the extension for the time being

**Comment by transgirlphoebe** [comment]
Laurelai is the username here on github,in case its needed.

**Comment by transgirlphoebe** [comment]
@Laurelai would you like to defend yourself now that you've deleted your Reddit and your Twitter accounts? Or would you like to go ahead and write out your confession so that you can be removed from the dev team

**Comment by Laurelai** [comment]
You people are fucking morons. I was never on the dev team. I dont even have the capability to code this. You guys are stupid. Stop harassing people. Get a life.

**Comment by MaeiMaei** [comment]
I'm not denying the accusations but this is kind of inappropriate for the repository.
https://shinigami-eyes.github.io/ lists a person called "Kiran" and otherwise, there is for all I know no proof that is or was a contributor, kind of like they mentioned.

**Comment by transgirlphoebe** [comment]
> I'm not denying the accusations but this is kind of inappropriate for the repository. https://shinigami-eyes.github.io/ lists a person called "Kiran" and otherwise, there is for all I know no proof that Laurelai is or was a contributor, kind of like they mentioned. ![image](https://user-images.githubusercontent.com/36708517/156949401-4888c068-5a9d-4f56-9413-cac77dec6a87.png)

not able to contribute but shes able to comment to this issue,sounds like a lotta lying going on here

**Comment by transgirlphoebe** [comment]
> You people are fucking morons. I was never on the dev team. I dont even have the capability to code this. You guys are stupid. Stop harassing people. Get a life.

youre not capable of coding this cause youre too busy fucking drugged Trans women,which you even didnt deny which is funny,thanks for the now archived implicit confession

**Comment by Laurelai** [comment]
I didnt do any of those things either? You people are insane. Absolutely bug nuts insane.

**Comment by Laurelai** [comment]
And since were you know, hitting below the belt here. Hello Phoebe Bradley. Stop being racist on twitter. https://twitter.com/transgirlphoebe/status/1494466658471141380

**Comment by transgirlphoebe** [comment]
> And since were you know, hitting below the belt here. Hello Phoebe Bradley. Stop being racist on twitter. https://twitter.com/transgirlphoebe/status/1494466658471141380

funny,you deny the fact after i point out that you didnt deny it. i actually dont use that twitter account and i already apologized to those i was unintentiolly racist towards.

**Comment by Laurelai** [comment]
Youre a stupid fucker arent you. Phoebe Bradley. If i was managing this repo i could delete this thread and ban you from it. Youre arguments are just as stupid as you are. Phoebe Bradley. Now everyone will firever connect your name. Phoebe Bradley. To this username. Stupid Phoebe Bradley.

**Comment by Laurelai** [comment]
And all the kiwifarms shitheads who follow me around to look for ways to attack me? Well now. Phoebe Bradley. They know your name now too. Have fun!

**Comment by transgirlphoebe** [comment]
> Youre a stupid fucker arent you. Phoebe Bradley. If i was managing this repo i could delete this thread and ban you from it. Youre arguments are just as stupid as you are. Phoebe Bradley. Now everyone will firever connect your name. Phoebe Bradley. To this username. Stupid Phoebe Bradley.

well the kiwifarms fuckheads can see you backpedaling-publicly spazzing-now that ive pointed out you didnt deny it originally. So tell me more how im the stupid one

**Comment by Laurelai** [comment]
They already hate me you dipshit. They already think this of me. None of this is new. Now they know you and they dont care whose side youre on :D

**Comment by transgirlphoebe** [comment]
> They already hate me you dipshit. They already think this of me. None of this is new. Now they know you and they dont care whose side youre on :D

they can know me alll they want to,i havent changed my legal name yet so good luck doxxing me or w/e

**Comment by digital-diplomat** [comment]
Just to add a bit of context here, I personally have a GitHub account because I have _just_ enough know-how to put together some neat little tools, and I have an interest in making suggestions regarding FOSS.

I do *not* have the necessary skills to actually contribute to this repo, save for minor edits to grammar and such. I *do* know how to comment on issues, as you can see.

> shes known to hide,and kiran is anonymous so you have zero proof that it ISNT her under a psudonym @MaeiMaei

That's not how evidence and accusations work. You can't prove she's *not* using a pseudonym in the same way that I can't prove I'm *not* an FBI agent. The burden of proof lies with the person making the claim.

This is not enough evidence that Laurelai is a major player on this extension. She is a trans person who, like the rest of us, has a vested interest in using this extension for her own safety online, so I don't doubt she's *commented* before. I *do* have my doubts about her having contributed code.

**Note:** I am not commenting on the serious allegations levied against Laurelai, only indicating that there is insufficient evidence to claim that LB has been involved in changes to *this extension's* code.

@Laurelai, I don't know enough about your situation to have a definite opinion on what crimes you have or have not committed, but I *do* know that given the amount of hot water you're in — combined with the blow-up around Eightpoint/"Slaanesh" on Mastodon — arguing in GitHub threads about your supposed use of anonymity to slide back into queer spaces is NOT a good look. The best PR move in situations like this is really just to say nothing, let people believe whatever, and move on, but that's just my unsolicited advice. Take it or leave it.

**Comment by Laurelai** [comment]
> Just to add a bit of context here, I personally have a GitHub account because I have _just_ enough know-how to put together some neat little tools, and I have an interest in making suggestions regarding FOSS.
> 
> I do _not_ have the necessary skills to actually contribute to this repo, save for minor edits to grammar and such. I _do_ know how to comment on issues, as you can see.
> 
> > shes known to hide,and kiran is anonymous so you have zero proof that it ISNT her under a psudonym @MaeiMaei
> 
> That's not how evidence and accusations work. You can't prove she's _not_ using a pseudonym in the same way that I can't prove I'm _not_ an FBI agent. The burden of proof lies with the person making the claim.
> 
> This is not enough evidence that Laurelai is a major player on this extension. She is a trans person who, like the rest of us, has a vested interest in using this extension for her own safety online, so I don't doubt she's _commented_ before. I _do_ have my doubts about her having contributed code.
> 
> **Note:** I am not commenting on the serious allegations levied against Laurelai, only indicating that there is insufficient evidence to claim that LB has been involved in changes to _this extension's_ code.
> 
> @Laurelai, I don't know enough about your situation to have a definite opinion on what crimes you have or have not committed, but I _do_ know that given the amount of hot water you're in — combined with the blow-up around Eightpoint/"Slaanesh" on Mastodon — arguing in GitHub threads about your supposed use of anonymity to slide back into queer spaces is NOT a good look. The best PR move in situations like this is really just to say nothing, let people believe whatever, and move on, but that's just my unsolicited advice. Take it or leave it.

So if I say nothing and the creatior eventually reveals themselves ill be accused of allowing people to think they are me maliciously to see them get attacked instead of me. If I speak out its "not a good look"

Shut the fuck up with this double standard bullshit.

**Comment by Laurelai** [comment]
Just leave me alone and keep my fucking name out of your mouth. You dont know shit.

**Comment by digital-diplomat** [comment]
Totally fair, you have no obligation to follow my advice and I'm *not* familiar with most of the situation. I'm just saying quit while you're ahead.

I will give no further input, just that I agree you are unlikely to have been a major dev on this project and that people need to stop repeating this obviously TERF-propagated talking point.

**Comment by Laurelai** [comment]
Ive never been ahead, Its presumed guilty even if proven otherwise. Guilty if im silent, guilty if i speak out. Guilty for existing. I pray you never experience this.

**Comment by LiEnby** [comment]
> > Youre a stupid fucker arent you. Phoebe Bradley. If i was managing this repo i could delete this thread and ban you from it. Youre arguments are just as stupid as you are. Phoebe Bradley. Now everyone will firever connect your name. Phoebe Bradley. To this username. Stupid Phoebe Bradley.
> 
> well the kiwifarms fuckheads can see you backpedaling-publicly spazzing-now that ive pointed out you didnt deny it originally. So tell me more how im the stupid one
> 
> https://archive.ph/7YbY8
> 
> let the kiwifarmers permanently see you like this

kiwifarms hates anyone who is transgender, for being transgender,  and they are responsible for multiple deaths-  they intentionally try drive people to fucking kill themselves. its an trans/other minorities hate site; if your pulling shit from fucking kiwifarms you might as well be pulling them out of your ass..
