### ISSUE TITLE
Destiny (streamer) is marked as trans friendly, but is not

### ISSUE THREAD

**Issue by weckd** [shinigami-eyes/shinigami-eyes#75]
[r/destiny getting transphobic after streamer Destiny is banned from Twitch for hate : AgainstHateSubreddits](https://www.reddit.com/r/AgainstHateSubreddits/comments/tpxjx9/rdestiny_getting_transphobic_after_streamer/)

[Is streamer Destiny Transphobic? : asktransgender](https://www.reddit.com/r/asktransgender/comments/tvu5zi/is_streamer_destiny_transphobic/)

Two posts I found that sum it up.

I have gone through the subreddit, and the community makes baseless defences and twists his words.

An example post: [Destiny: "... if trans women were women they wouldn't need hormones or surgery." Is he becoming more transphobic, or did he always have this position? : Destiny](https://www.reddit.com/r/Destiny/comments/uh9k8l/destiny_if_trans_women_were_women_they_wouldnt/)

I dont watch his streams, from the post this was in context of trans women in women's sports, and the community turns it into "he meant that just saying trans women are women doesnt solve all problems they face"
"its like making distinction of black men and men to tackle specific issues"

Either ways, its a shit take, because while passing shouldnt be forced on people, its still something trans* people have to comply to in order to be safe.

Many of the community reactions to destiny being transphobic are like this, twisted and misleading. 
He may have been once vocal for trans rights (as per the community) but now he isnt.

Not to mention him using ableist language and racial slurs against anyone he disagrees with is pretty problematic itself, but since this extension is specific to trans rights, I understand this wouldnt be enough reason.

At the very least I think he shouldnt be marked pro-trans if not anti-trans. He seems to have a mixed history so I think at least no marking instead of anti-trans is doable?

**Comment by Rexogamer** [comment]
This repository does not host/handled the actual data used by the extension itself. I would personally mark Destiny as neutral/anti-trans, but this should be handled by using the extension and not here.

**Comment by weckd** [comment]
I have done that. I raised an issue because he has been marked trans friendly, and there isn't any other place to report wrong tags afaik.

**Comment by Rexogamer** [comment]
You can clear/modify how someone is marked by right-clicking on a relevant link and (in this case) selecting "Mark as anti-trans" or "Clear".
