### ISSUE TITLE
github commit dates are marked transphobic 

### ISSUE THREAD

**Issue by soredake** [shinigami-eyes/shinigami-eyes#96]
![image](https://github.com/shinigami-eyes/shinigami-eyes/assets/5204968/1fde82db-04ee-4e4c-bddf-3fd2540f40fd)
Can be tested on this page https://github.com/soupslurpr/BeauTyXT

**Comment by juanigaray** [comment]
I can't reproduce it on my machine. Did you mark a the user as transphobic locally?
![image](https://github.com/shinigami-eyes/shinigami-eyes/assets/31663056/dfc15352-5234-4102-99c6-35cb91988caa)

**Comment by juanigaray** [comment]
Also I see a pattern in your screenshot. The commits from >=2 weeks ago are a different shade. Do you have any extensions installed for Github?

**Comment by soredake** [comment]
>Did you mark the user as transphobic locally?

No.

>Do you have any extensions installed for Github?

Yes, https://addons.mozilla.org/ru/firefox/addon/refined-github-/

**Comment by juanigaray** [comment]
Does disabling the add-on do anything? In case it doesn't, I'd look into the HTML classnames to see if the commits have `assigned-label-transphobic` or some such classname around them
